### PR TITLE
Add configurable event polling interval via constructor

### PR DESCRIPTION
**Pull request by Weeesel**
As addressed by #20 this adds a configuralble polling interval for the event loop with a bigger default time to lower CPU usage.

### CODE REVIEW

**Comment by linusg** [comment]
Perfect, thank you! Do you intend do make further changes (WIP)? I'd be happy to merge as-is.

**Comment by Weeesel** [comment]
I encountered some problems and dont think its ready to merge yet.

#### Problems
For high values like `poll_interval=0.1` I get some strange laggy behaviour. I'm investigating whats going on...

**Comment by Weeesel** [comment]
So, I found the time to get into this more and found a slightly different solution.

#### New approach
We move the waiting via `time.sleep` into a blocking call of [`select.select`](https://docs.python.org/3/library/select.html#select.select). With this we can set very high timeout values without loosing response time while having virtually no CPU load when idling. I went so far to set the default to `1.0`. Maybe this is to much but I see this atm only affecting the quitting time, when we want to shutdown the event thread... 🤔 

#### Problems with the old approach
With big values the slow polling would lead to the driver filling up the event queue and eventually [dropping events and generating lots of those init events](https://www.kernel.org/doc/Documentation/input/joystick-api.txt). On top of this, this full queue and the init events would be slowly be processed by us until we feel respones from the controller again... 🐢🐢🐢

**Comment by SeeringPhil** [comment]
So the default of 1.0 doesn't mean that you'll only receive updates at a 1 Hz rate?

Because I don't see that many use cases where a 1s delay on a gamepad would be the best default value 🤔 
Taking into consideration the [average human reaction time](https://humanbenchmark.com/tests/reactiontime#:~:text=While%20an%20average%20human%20reaction,5%20clicks%20and%20then%20save.), I think the best bet would probably be something around 0.2 - 0.3 seconds to fit most scenarios. (This is assuming that the 1s polling **would** slow down stuff, if it doesn't then I'm sorry, don't mind me 😅

**Review by linusg — APPROVED** [review]
Now that's a nice solution!

**Comment by Weeesel** [comment]
> 
> 
> So the default of 1.0 doesn't mean that you'll only receive updates at a 1 Hz rate?

Nope, the updates come in as fast as the controller and your fingers can create them ⚡

**Pull request merged**
